# Generated by Django 3.2.2 on 2021-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, to='Wallet.Wallet'),
        ),
    ]
